# Generated by Django 5.2 on 2025-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_schema", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default=str, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hashed_password",
            field=models.CharField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default=str),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="users",
        ),
    ]
