# Generated by Django 5.2 on 2025-05-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_schema", "0002_remove_userprofile_user_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
