# Generated by Django 5.2 on 2025-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_schema", "0003_userprofile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
