# Generated by Django 5.2 on 2025-05-06 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_schema", "0004_alter_userprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="notifications",
        ),
    ]
